Add erlang.mk support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,17 +46,25 @@ export PATH
 
 cd $build
 
-if [ ! -e "rebar" ]; then
-  echo "-----> Installing Rebar from buildpack"
-  cp ${bpdir}/opt/rebar ./
-fi
-
-echo "-----> Building with Rebar"
 unset GIT_DIR
-./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-  echo "-----> Build failed"
-  exit 1
+if [ -f erlang.mk ]; then
+    echo "-----> Building with Make using erlang.mk"
+    make 2>&1 | sed -u 's/^/       /'
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        echo "-----> Build failed"
+        exit 1
+    fi
+else
+    if [ ! -e "rebar" ]; then
+        echo "-----> Installing Rebar from buildpack"
+        cp ${bpdir}/opt/rebar ./
+    fi
+    echo "-----> Building with Rebar"
+    ./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        echo "-----> Build failed"
+        exit 1
+    fi
 fi
 
 if [ -f ${bpdir}/opt/otp.sh ]; then
